=== Nepochatova-Polina/Distributed_Calc/src/com/company/Module2/Lab1/resources/MusicShop.dtd
<!ELEMENT MusicShop (Item+)>
        <!ELEMENT Item (artistName,Albums)>
        <!ELEMENT artistName (#PCDATA)>
        <!ELEMENT Albums (Album+)>
        <!ELEMENT Album (albumID,albumName,numOfSongs,numOfCopies,type)>
        <!ELEMENT albumID (#PCDATA)>
        <!ELEMENT albumName (#PCDATA)>
        <!ELEMENT numOfSongs (#PCDATA)>
        <!ELEMENT numOfCopies (#PCDATA)>
        <!ELEMENT type (#PCDATA)>

=== Nepochatova-Polina/Distributed_Calc/src/com/company/Module2/Lab1/resources/MusicShop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE MusicShop SYSTEM "MusicShop.dtd">
<MusicShop>
    <Item>
        <artistName>Ivanushka</artistName>
        <Albums>
            <Album>
                <albumID>269422</albumID>
                <albumName>Aduvanchiki</albumName>
                <numOfSongs>22</numOfSongs>
                <numOfCopies>1095</numOfCopies>
                <type>full</type>
            </Album>
            <Album>
                <albumID>22222</albumID>
                <albumName>Vasilki</albumName>
                <numOfSongs>32</numOfSongs>
                <numOfCopies>115</numOfCopies>
                <type>full</type>
            </Album>
        </Albums>
    </Item>
    <Item>
        <artistName>Petroff</artistName>
        <Albums>
            <Album>
                <albumID>33333</albumID>
                <albumName>Romashki</albumName>
                <numOfSongs>5</numOfSongs>
                <numOfCopies>105</numOfCopies>
                <type>mini</type>
            </Album>
        </Albums>
    </Item>
</MusicShop>
